"""
data.py — Static seed data simulating HUD / TDHCA / 211 Texas records.
In production, replace COMPLEXES with live API calls (see Story 3).
"""

VISIT_STATUSES = [
    "Visited",
    "No Answer",
    "Follow-Up Needed",
    "Partnership Established",
]

COMPLEXES = [
    # ── Lewisville ────────────────────────────────────────────────────────────
    {
        "id": "LVL001",
        "name": "Lakeside Senior Village",
        "address": "1200 Lakeview Dr",
        "city": "Lewisville",
        "state": "TX",
        "zip": "75067",
        "phone": "(972) 555-0101",
        "manager": "Sandra Reyes",
        "unit_count": 120,
        "designations": ["HUD", "Section 8"],
        "source": "HUD Public Housing Database",
        "last_updated": "2025-11-01",
    },
    {
        "id": "LVL002",
        "name": "Villas at Valley Ranch",
        "address": "400 Valley Ranch Pkwy",
        "city": "Lewisville",
        "state": "TX",
        "zip": "75067",
        "phone": "(972) 555-0182",
        "manager": None,
        "unit_count": 88,
        "designations": ["Tax Credit"],
        "source": "TDHCA",
        "last_updated": "2025-10-15",
    },
    {
        "id": "LVL003",
        "name": "Heritage Park Apartments",
        "address": "900 E Corporate Dr",
        "city": "Lewisville",
        "state": "TX",
        "zip": "75057",
        "phone": None,
        "manager": "James O'Brien",
        "unit_count": 64,
        "designations": ["Section 8"],
        "source": "211 Texas",
        "last_updated": "2025-09-20",
    },
    # ── Carrollton ────────────────────────────────────────────────────────────
    {
        "id": "CTN001",
        "name": "Carrollton Senior Commons",
        "address": "2700 N Josey Ln",
        "city": "Carrollton",
        "state": "TX",
        "zip": "75007",
        "phone": "(972) 555-0234",
        "manager": "Maria Gonzalez",
        "unit_count": 150,
        "designations": ["HUD", "Tax Credit"],
        "source": "HUD Public Housing Database",
        "last_updated": "2025-11-10",
    },
    {
        "id": "CTN002",
        "name": "Bent Tree Affordable Living",
        "address": "1845 W Belt Line Rd",
        "city": "Carrollton",
        "state": "TX",
        "zip": "75006",
        "phone": "(972) 555-0278",
        "manager": None,
        "unit_count": 96,
        "designations": ["Section 8"],
        "source": "TDHCA",
        "last_updated": "2025-10-05",
    },
    {
        "id": "CTN003",
        "name": "Elm Creek Terrace",
        "address": "3300 Keller Springs Rd",
        "city": "Carrollton",
        "state": "TX",
        "zip": "75006",
        "phone": "(972) 555-0399",
        "manager": "Tom Nguyen",
        "unit_count": 72,
        "designations": ["Tax Credit"],
        "source": "211 Texas",
        "last_updated": "2025-08-30",
    },
    # ── Flower Mound ──────────────────────────────────────────────────────────
    {
        "id": "FLM001",
        "name": "Magnolia Place Senior Housing",
        "address": "500 Flower Mound Rd",
        "city": "Flower Mound",
        "state": "TX",
        "zip": "75028",
        "phone": "(972) 555-0451",
        "manager": "Claire Hendricks",
        "unit_count": 80,
        "designations": ["HUD"],
        "source": "HUD Public Housing Database",
        "last_updated": "2025-11-01",
    },
    {
        "id": "FLM002",
        "name": "Prairie Wind Affordable Homes",
        "address": "1100 Justin Rd",
        "city": "Flower Mound",
        "state": "TX",
        "zip": "75028",
        "phone": None,
        "manager": None,
        "unit_count": None,
        "designations": ["Tax Credit"],
        "source": "TDHCA",
        "last_updated": "2025-09-14",
    },
    # ── Denton ────────────────────────────────────────────────────────────────
    {
        "id": "DTN001",
        "name": "Denton County Housing Authority — Main",
        "address": "320 E McKinney St",
        "city": "Denton",
        "state": "TX",
        "zip": "76201",
        "phone": "(940) 555-0511",
        "manager": "Robert Hale",
        "unit_count": 200,
        "designations": ["HUD", "Section 8"],
        "source": "HUD Public Housing Database",
        "last_updated": "2025-11-12",
    },
    {
        "id": "DTN002",
        "name": "Fry Street Commons",
        "address": "710 Fry St",
        "city": "Denton",
        "state": "TX",
        "zip": "76201",
        "phone": "(940) 555-0598",
        "manager": "Angela Park",
        "unit_count": 110,
        "designations": ["Section 8", "Tax Credit"],
        "source": "211 Texas",
        "last_updated": "2025-10-22",
    },
    {
        "id": "DTN003",
        "name": "Meadowbrook Village",
        "address": "2200 W University Dr",
        "city": "Denton",
        "state": "TX",
        "zip": "76201",
        "phone": None,
        "manager": "Luis Fernandez",
        "unit_count": 60,
        "designations": ["Tax Credit"],
        "source": "TDHCA",
        "last_updated": "2025-07-18",
    },
    {
        "id": "DTN004",
        "name": "North Texas Senior Residences",
        "address": "4401 Scripture St",
        "city": "Denton",
        "state": "TX",
        "zip": "76207",
        "phone": "(940) 555-0621",
        "manager": None,
        "unit_count": 175,
        "designations": ["HUD"],
        "source": "HUD Public Housing Database",
        "last_updated": "2025-11-05",
    },
]
